### ISSUE TITLE
fail to fetch or update

### ISSUE THREAD

**Issue by kaal-dam** [flippelt/WnG-Apocrypha-FoundryVTT#10]
Hello, tried to update all my module and plugin today

got this error 

caught (in promise) Error: An unexpected error occurred when downloading file https://github.com/flippelt/WnG-Apocrypha-FoundryVTT/releases/download/MekhanicalUpdate2.1/wng-apocrypha.zip: Not Found
    at fetchWithTimeout (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/http.mjs:48:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/files/downloader.mjs:1:616

Have a nice day

**Comment by flippelt** [comment]
Hello, sorry for taking so long to answer.
I think I found the problem with the RAR compression and changed for ZIP, could you please check if it's working?

**Comment by kaal-dam** [comment]
Fixed, thank you, no problem for the delay, I'm not even actively running W&G right now but I was making a routine update of my library so I thought I would be good to report it
